version: '3.8'

x-besu-def: &besu-def
  image: hyperledger/besu:latest
  networks:
    - qbft-network

services:
  node1:
    <<: *besu-def
    container_name: besu-node1
    command:
      - --data-path=/data
      - --genesis-file=/genesis.json
      - --network-id=1337
      - --rpc-http-enabled
      - --rpc-http-api=ETH,NET,QBFT
      - --host-allowlist=*
      - --rpc-http-cors-origins=all
      - --profile=ENTERPRISE
    volumes:
      - ./genesis.json:/genesis.json
      - ./node1/data:/data
    ports:
      - '8545:8545'
    networks:
      qbft-network:
        ipv4_address: 172.16.239.11

  node2:
    <<: *besu-def
    container_name: besu-node2
    command:
      - --data-path=/data
      - --genesis-file=/genesis.json
      - --bootnodes=enode://c69a99de7ea8ca0ed47b96a623ceb26126fc8b098ef6026c7639a9d4041c907f26c0d584e9f91dba438f5fb581b28a36c166915d5d27f30d1cdbee6c3c935d38@172.16.239.11:30303
      - --network-id=1337
      - --rpc-http-enabled
      - --rpc-http-api=ETH,NET,QBFT
      - --host-allowlist=*
      - --rpc-http-cors-origins=all
      - --profile=ENTERPRISE
    volumes:
      - ./genesis.json:/genesis.json
      - ./node2/data:/data
    ports:
      - '8546:8545'
    depends_on:
      - node1

  node3:
    <<: *besu-def
    container_name: besu-node3
    command:
      - --data-path=/data
      - --genesis-file=/genesis.json
      - --bootnodes=enode://c69a99de7ea8ca0ed47b96a623ceb26126fc8b098ef6026c7639a9d4041c907f26c0d584e9f91dba438f5fb581b28a36c166915d5d27f30d1cdbee6c3c935d38@172.16.239.11:30303
      - --network-id=1337
      - --rpc-http-enabled
      - --rpc-http-api=ETH,NET,QBFT
      - --host-allowlist=*
      - --rpc-http-cors-origins=all
      - --profile=ENTERPRISE
    volumes:
      - ./genesis.json:/genesis.json
      - ./node3/data:/data
    ports:
      - '8547:8545'
    depends_on:
      - node1

  node4:
    <<: *besu-def
    container_name: besu-node4
    command:
      - --data-path=/data
      - --genesis-file=/genesis.json
      - --bootnodes=enode://c69a99de7ea8ca0ed47b96a623ceb26126fc8b098ef6026c7639a9d4041c907f26c0d584e9f91dba438f5fb581b28a36c166915d5d27f30d1cdbee6c3c935d38@172.16.239.11:30303
      - --network-id=1337
      - --rpc-http-enabled
      - --rpc-http-api=ETH,NET,QBFT
      - --host-allowlist=*
      - --rpc-http-cors-origins=all
      - --profile=ENTERPRISE
    volumes:
      - ./genesis.json:/genesis.json
      - ./node4/data:/data
    ports:
      - '8548:8545'
    depends_on:
      - node1

networks:
  qbft-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
